### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by kevinvenclovas** [prjseal/SlackBotMessages#3]
It would be really nice when we can upload images via url :D Thank you for sharing! Enjoy the coffee ;)

**Comment by prjseal** [comment]
Thank you for the coffee. I will be adding extra functionality to this package soon and converting it to .NET Standard 2.0

**Comment by prjseal** [comment]
@kshopper93 I have rewritten the whole thing and released version 2.0

Take a look at the readme now and please try it out and let me know what you think. 

Paul

**Comment by kevinvenclovas** [comment]
Perfekt! Thank you
![image](https://user-images.githubusercontent.com/7681603/59909317-ba264000-940f-11e9-90c1-0ee5de151d43.png)

**Comment by prjseal** [comment]
Awesome to see. Thanks.
